language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

  # Decrypt and unarchive Maven and Google Cloud Storage credentials.
  - openssl aes-256-cbc -K $encrypted_f5821d4f7269_key -iv $encrypted_f5821d4f7269_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

script:
  - ./gradlew check --stacktrace

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./config/scripts/publish-artifacts.sh
  - ./config/scripts/publish-artifacts.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
